# Generated by Django 4.2 on 2023-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
